# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Clône du dépôt GIT
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Configuration .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Installation des dépendances
      run: dotnet restore
    - name: Compilation
      run: dotnet build --no-restore
    - name: validation des tests unitaires
      run: dotnet test --no-build --verbosity normal
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

